config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  get 'relationships/create'

  get 'relationships/destroy'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  get 'blogs' => 'blogs#index'
  get 'contacts' => 'contacts#new'

  resources :blogs do
    resources :comments
      
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end
  
  resources :poems, only: [:index, :show]
  
  resources :users, only: [:index, :show]
  
  resources :relationships, only: [:create, :destroy]
  root 'top#index'
  
  resources :conversations do
    resources :messages
  end

  
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/poem.rb
class Poem
  include Her::Model
  
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  
  def index
    @poems = Poem.all
  end
  
  def show
    @poem = Poem.find(params[:id])
  end

end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <h1>ポエム一覧</h1>
    <% @poems.each do |poem| %>
    <div class="row">
      <h4><strong><%= poem.title %></strong></h4>
      <p><%= poem.content %></p>
      <div class="user-name btn">
        <%= poem.auther %>
      </div>
      <%= link_to "詳細", poem_path(poem.id), class: 'btn btn-default btn-sm btn-success' %>
    </div>
    <% end %>
  </div>
  <div id="page-top-blogs-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
  </div>
</div>

app/views/poems/show.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <h1>ポエム</h1>
    <div class="row">
      <h4><strong><%= @poem.title %></strong></h4>
      <p><%= @poem.content %></p>
      <div class="user-name btn">
        <%= @poem.auther %>
      </div>
      <%= link_to "一覧", poems_path, class: 'btn btn-default btn-sm btn-success' %>
    </div>
  </div>
</div>